# Generated by Django 2.0 on 2019-01-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190126_0145'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elmusicuser',
            name='fav_albums',
            field=models.ManyToManyField(to='main.Album'),
        ),
        migrations.AddField(
            model_name='elmusicuser',
            name='fav_artists',
            field=models.ManyToManyField(to='main.Artist'),
        ),
        migrations.AddField(
            model_name='elmusicuser',
            name='fav_songs',
            field=models.ManyToManyField(to='main.Song'),
        ),
    ]
