# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-23 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='song',
            name='file_src',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
