# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-23 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171223_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='file_type',
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.FileField(upload_to='songs/'),
        ),
    ]
