# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-23 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171223_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='logo',
            field=models.FileField(upload_to='albums/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.FileField(upload_to='artists/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file_src',
            field=models.FileField(upload_to='songs/'),
        ),
    ]
