# Generated by Django 2.0 on 2019-01-26 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171223_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=3)),
                ('body', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='is_fav',
        ),
        migrations.AddField(
            model_name='album',
            name='desc',
            field=models.TextField(default='', max_length=15000),
        ),
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.TextField(default='', max_length=15000),
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(default='', max_length=15000),
        ),
        migrations.AddField(
            model_name='review',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Album'),
        ),
        migrations.AddField(
            model_name='review',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Artist'),
        ),
        migrations.AddField(
            model_name='review',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Song'),
        ),
    ]
